// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addnewforeignkey1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewforeignkey1));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261914214_addnewforeignkey1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
